---
name: Build and Push Project to GCP
on:
  push:   
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: server-project
      PROJECT_ID: server-administration-422608
    steps: 
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@main
      with: 
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Image builds
      run: docker compose build

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

    # - name: Push Docker Image to Container Registry (GCR)
    #   env: 
    #     GIT_TAG: v0.1.0
    #   run: |- 
    #     docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
    #     docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
    #     docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
    #     docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

    - name: Push Docker Images to Container Registry (GCR)
      env: 
        GIT_TAG: v0.1.0
      run: |- 
        # services=(web api mongo)  # Replace with your service names
        # for service in "${services[@]}"; do
        #   docker tag $service:latest gcr.io/server-administration-422608/$service:latest
        #   docker tag $service:latest gcr.io/server-administration-422608/$service:$GIT_TAG
        #   docker push gcr.io/server-administration-422608/$service:latest
        #   docker push gcr.io/server-administration-422608/$service:$GIT_TAG
        # done
